### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value.

### ISSUE THREAD

**Issue by wbz7** [matacoder/wildberries-rest-api#3]
Traceback (most recent call last):
  File "/code/manage.py", line 22, in <module>
    main()
  File "/code/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 92, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/loader.py", line 53, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/loader.py", line 220, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
    if self.has_table():
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 55, in has_table
    with self.connection.cursor() as cursor:
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/dummy/base.py", line 20, in complain
    raise ImproperlyConfigured("settings.DATABASES is improperly configured. "
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.

141 static files copied to '/code/static'.
[2021-12-22 16:22:11 +0000] [12] [INFO] Starting gunicorn 20.1.0
[2021-12-22 16:22:11 +0000] [12] [INFO] Listening at: http://0.0.0.0:8000 (12)
[2021-12-22 16:22:11 +0000] [12] [INFO] Using worker: sync
[2021-12-22 16:22:11 +0000] [13] [INFO] Booting worker with pid: 13

**Comment by asokr** [comment]
Согласен. Поднять сервис не смог, можно опубликовать .env файлы, как я понимаю, настройки там :)

**Comment by matacoder** [comment]
https://github.com/matacoder/django-docker/blob/master/.env

**Comment by matacoder** [comment]
Обновил README, добавил инструкцию по `.env` файлу.

**Comment by SmirnovL** [comment]
@matacoder  Приветствую, установил всё по инструкции, но выдаёт ошибку (Windows 10)
![image](https://user-images.githubusercontent.com/95228126/148543954-28f11f95-e358-4afe-82a3-c1d9cb33722e.png)

wildberries-rest-api_django_1 - "standard_init_linux.go:228: exec user process caused: no such file or directory"
![image](https://user-images.githubusercontent.com/95228126/148544084-b9604ef2-067a-40ee-b5db-36cbdfda92de.png)

Если есть возможность подскажите как исправить
И такой вопрос, возможно ли запустить без докера, чисто через PyCharm

**Comment by matacoder** [comment]
Через пайчарм не запустить. У вас, похоже, не найден какой-то файл, возможно `entrypoint.sh`
